openapi: 3.0.0
info:
  title: Trabajo Práctico 1
  description: Una solución de DoH simplificada, implementando esta utilizando las herramientas...
  version: "1.0.0"

servers:
  - url: http://localhost:8080/api
    description: Servidor de desarrollo

tags:
  - name: "domains"
    description: "Resolución de dominios"
  - name: "custom-domains"
    description: "Alta, baja y modificación de dominios personalizados"

# Paths servidos por la aplicación
paths:
  /domains/{domain}:
    get:
      operationId: "api.domains.obtener_uno"
      tags:
        - "domains"
      summary: "Resolución de nombres de dominio"
      description: "Obtiene la IP asociada a un dominio en particular, pudiendo ser este un custom domain creado previamente."
      parameters:
        - in: path
          name: domain
          required: true
          schema:
            type: string
          description: "El domain del cual se quiere conocer su IP"
      responses:
        200:
          description: Operacion de lectura exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        404:
          description: 'Dominio no encontrado'
  /custom-domains:
    post:
      operationId: "api.domains.crear"
      tags:
        - "custom-domains"
      summary: "Alta de un custom domain"
      description: "Crea una entrada para sobreescribir la IP de un dominio en particular"
      requestBody:
        required: true
        x-body-name: 'domain'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputDomain'
      responses:
        201:
          description: "Se creo el custom-domain correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        400:
          description: 'IP duplicada o falta un parametro'
    get:
      operationId: api.domains.query_custom_domains
      tags:
        - "custom-domains"
      summary: "Búsqueda de custom-domains"
      description: "Permite el filtrado de custom-domains mediante el parámetro 'q'"
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: "dominio a buscar"
          required: false
      responses:
        200:
            description: ""
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Domain'
  /custom-domains/{domain}:
    put:
      operationId: "api.domains.editar"
      tags:
        - "custom-domains"
      summary: "Edición de un dominio en sistema"
      description: "Se modifica un custom-domain ya existente"
      parameters:
        - in: path
          name: domain
          required: true
          schema:
            type: string
          description: Domain al cual se quiere agregar un custom-domain
      requestBody:
        required: true
        x-body-name: 'domain'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputDomain'
      responses:
        200:
          description: "Se editó el custom-domain correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        404:
          description: "El dominio no existe"
        400:
          description: "Cuerpo mal formado"
    delete:
      operationId: "api.domains.borrar"
      tags:
        - "custom-domains"
      summary: "Borrado de un custom domain"
      description: "Borra, si existe, un custom domain"
      parameters:
        - in: path
          name: domain
          required: true
          schema:
            type: string
          description: "El nombre del domain que se quiere borrar"
      responses:
        200:
          description: "Operación de borrado exitosa"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseDomain'
        404:
          description: "Domain no encontrado"

# Declaración de tipos de datos
components:
  schemas:
    Domain:
      type: object
      properties:
        domain:
          type: string
        ip:
          type: string
        custom:
          type: boolean
    InputDomain:
      type: object
      properties:
        domain:
          type: string
        ip:
          type: string
    ResponseDomain:
      type: object
      properties:
        domain:
          type: string
