openapi: 3.0.0
info:
	version: "1.0.0"
	title: API Trabajo Práctico 1
	description: Una solución de DoH simplificada, implementando esta utilizando las herramientas...

servers:
	- url: http://localhost:8080/api
		description: Servidor de desarrollo

# Paths servidos por la aplicación
paths:
	/domains/{domain}:
		get​​:
			operationId: "TO_DO_DEFINIR"
			tags:
				- "Dominios"
			summary: "IP asociada a un dominio en particular"
			description: "Devuelve la IP asociada a un dominio en particular. Si en hostname tiene varias IPs distintas, el servicio deberá devolver sólo una. Sin embargo, si se vuelve a pedir la IP de ese dominio​, se alternará entre las que provee el resolver de DNS en forma de round robin"
			parameters:
				- in: path
					name: domain
					required: true
					schema:
						type: string
					description: El hostname del dominio a resolver.
			responses:
				200:
					description: "Resolución exitosa"
					content:
						application/json:
							schema:
								$ref: '#/components/schemas/Domain'
				404:
					description: "Dominio no encontrado"
	/custom-domain:
		post​:
			operationId: "TO_DO_DEFINIR"
			tags:
				- "Dominios"
			summary: "Crea una entrada para sobreescribir la IP de un dominio en particular."
			description: ""
      requestBody:
        required: true
        x-body-name: 'dominio'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputCustomDomain'
			responses:
				201:
					description: "Se creó la entrada correctamente"
					content:
						application/json:
							schema:
								$ref: '#/components/schemas/Domain'
				400:
					description: ""
					content:
						application/json:
							schema:
								$ref: '#/components/schemas/InputCustomDomain'
	/custom-domain/{domain}:
		put​:
			operationId: "TO_DO_DEFINIR"
			tags:
				- "Dominios"
			summary:
			description:
			responses:
				200:
					description: "Se editó el dominio correctamente"
					content:
						application/json:
							schema:
								$ref: '#/components/schemas/InputCustomDomain'
				400:
					description: "Request mal formado"
					content:
						application/json:
							schema:
								$ref: '#/components/schemas/InputCustomDomain'
				404:
					description: "No se encuentra el dominio en el sistema"
		delete​:
			operationId: "TO_DO_DEFINIR"
			tags:
				- "Dominios"
			summary: "Borra un dominio existente en el sistema"
			description: ""
			responses:
				200:
					description: "Dominio no encontrado"
					content:
						application/json:
							schema:
								$ref: '#/components/schemas/DomainResponse'
				404:
					description: "Dominio inexistente"
	/custom-domain?q={string}:
		get​:
			operationId: "TO_DO_DEFINIR"
			tags:
				- "Dominios"
			summary: "Obtiene todos los dominios en el sistema"
			description: "Se provee filtro 'q' para obtener todos los dominios que contengan el string pasado como parámetro"
			responses:
				200:
					description: "Dominios encontrados"
					content:
						application/json:
							schema:
								type: array
								items:
									$ref: '#/components/schemas/Domain'
# Declaración de tipos de datos
components:
	schemas:
		Domain:
			type: "object"
			properties:
				domain:
					type: "string"
				ip:
					type: "string"
				custom:
					type: "boolean"
		InputCustomDomain:
			type: "object"
			properties:
				domain:
					type: "string"
				ip:
					type: "string"
		DomainResponse:
			type: "string"